BASE_URL_DEV = 'https://devapi.ed.rt.ru'
BASE_URL_TEST = 'https://testapi.ed.rt.ru'
CREATE_TASK = '/edogovor/v1/task/'
CREATE_TASK_V2 = '/edogovor/v2/task/'
CREATE_TASK_V3 = '/edogovor/v3/task/'
EDOGOVOR = '/edogovor/v1/'
SEARCH_V1 = '/edogovor/v1/task/search?identificationValue='
SEARCH_V2 = '/edogovor/v2/task/search?account='
SEARCH_V3_ONE_PART = '/edogovor/v3/task/search?account='
SEARCH_V3_TWO_PART = '&order='
SEARCH_V4 = '/edogovor/v4/task/search?phone='
UPLOAD = '/fileLinks'
PROVIDE = '/edogovor/v3/provide/'

BASE_URL_FVNO = 'http://devapp.homeinternet.rt.ru/api/v1/'
CAMUNDA_URL_DEV = 'http://10.42.110.215:8001/rest/'
